using './main.bicep'
param location = 'francecentral'
param resourceGroupName = 'RG-APPLICATION-GATEWAY-FOR-CONTAINER'
param environmentName = 'dev'
param resourceSuffix = 'datasynchro-app'
param keyVaultCertificatesOfficerObjectId = '7abf4c5b-9638-4ec4-b830-ede0a8031b25'
