using './main.bicep'
param location = 'francecentral'
param resourceGroupName = 'RG-APPLICATION-GATEWAY-FOR-CONTAINER'
param environmentName = 'dev'
param resourceSuffix = 'datasynchro-app'
param keyVaultCertificatesOfficerObjectId = '{{KEY_VAULT_CERTIFICATES_OFFICER_OBJECT_ID}}'
