apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot-sa
  namespace: azure-resources
  annotations:
    azure.workload.identity/client-id: "15d279b6-5ea0-4a27-80b4-af67115998de" # "<CLIENT_ID_OF_WorkloadManagedIdentity>"

