apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-app
  namespace: azure-resources
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: otel-demo-app
          image: datasynchroacr.azurecr.io/web-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: WEBAPI_URL
              value : http://webapi-service