apiVersion: v1
kind: ServiceAccount
metadata:
  name: datasynchro-app-sa
  namespace: datasynchro-app
  annotations:
    azure.workload.identity/client-id: "${AZURE_APP_IDENTITY_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
