apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datasynchro-app.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ required "azure.appIdentityClientId is required" .Values.azure.appIdentityClientId | quote }}
    keyvaultName: {{ required "azure.keyVaultName is required" .Values.azure.keyVaultName | quote }}
    tenantId: {{ required "azure.tenantId is required" .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProviderClass.keyVaultSecretName }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secretProviderClass.keyVaultCertificateName }}
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: {{ .Values.secretProviderClass.secretName }}
    type: Opaque
    data:
    - objectName: {{ .Values.secretProviderClass.keyVaultSecretName }}
      key: {{ .Values.secretProviderClass.secretKey }}
  - secretName: {{ .Values.secretProviderClass.tlsSecretName }}
    type: kubernetes.io/tls
    data:
    - objectName: {{ .Values.secretProviderClass.keyVaultCertificateName }}
      key: tls.key
    - objectName: {{ .Values.secretProviderClass.keyVaultCertificateName }}
      key: tls.crt
