{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datasynchro-app.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ required "azure.appIdentityClientId is required" .Values.azure.appIdentityClientId | quote }}
{{- end }}
