apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-workload-identity-key-vault
  namespace: azure-resources #${SERVICE_ACCOUNT_NAMESPACE}
  labels:
    app: sample-workload-identity-key-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-workload-identity-key-vault
  template:
    metadata:
      labels:
        app: sample-workload-identity-key-vault
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa #${SERVICE_ACCOUNT_NAME}
      containers:
        - name: oidc
          image: ghcr.io/azure/azure-workload-identity/msal-go
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: KEYVAULT_URL
              value: https://keyvault-workload-id-log.vault.azure.net #${KEYVAULT_URL}
            - name: SECRET_NAME
              value: my-secret-ds #${KEYVAULT_SECRET_NAME}
      nodeSelector:
        kubernetes.io/os: linux
