apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 8474d8e6-ce35-436e-9a50-713f896c1570 # "${USER_ASSIGNED_CLIENT_ID}"
  name: workload-identity-sa #"${SERVICE_ACCOUNT_NAME}"
  namespace: azure-resources #"${SERVICE_ACCOUNT_NAMESPACE}"